export enum SystemCode {
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  FORBIDDEN_RESOURCE = 'FORBIDDEN_RESOURCE',
  WRONG_USERNAME_PASSWORD = 'WRONG_USERNAME_PASSWORD',
  TEMPLATE_NOT_FOUND = 'TEMPLATE_NOT_FOUND',
  COUNTRY_NOT_FOUND = 'COUNTRY_NOT_FOUND',
}
